import { DifficultyLevel, PrismaClient } from '@prisma/client';
import { lessonCategoryMap } from '../../../../scripts/speaking-practice-category-mapping';

const prisma = new PrismaClient();

/**
 * Seed data for SpeakingPracticeLesson
 * 50+ lessons (10+ per level)
 */
export async function seedSpeakingPracticeLessons() {
  console.log('🎤 Seeding Speaking Practice Lessons...');

  const lessons = [
    // ==================== LEVEL 1: Words (10 lessons) ====================
    {
      level: 1,
      levelName: 'Words',
      difficulty: DifficultyLevel.beginner,
      orderIndex: 1,
      type: 'word',
      title: 'Animals',
      content: {
        items: ['cat', 'dog', 'bird', 'fish', 'horse', 'cow', 'pig', 'duck'],
        ai_prompts: ['Say: {word}', 'Repeat after me: {word}', 'Can you say: {word}?'],
      },
      passThreshold: 80,
      targetPhonemes: ['k', 't', 'd', 'g'],
      tags: ['animals', 'beginner'],
    },
    {
      level: 1,
      levelName: 'Words',
      difficulty: DifficultyLevel.beginner,
      orderIndex: 2,
      type: 'word',
      title: 'Colors',
      content: {
        items: ['red', 'blue', 'green', 'yellow', 'orange', 'purple', 'pink', 'black'],
        ai_prompts: ['What color is this? Say: {word}', 'Repeat: {word}'],
      },
      passThreshold: 80,
      targetPhonemes: ['r', 'l', 'b', 'p'],
      tags: ['colors', 'beginner'],
    },
    {
      level: 1,
      levelName: 'Words',
      difficulty: DifficultyLevel.beginner,
      orderIndex: 3,
      type: 'word',
      title: 'Numbers 1-10',
      content: {
        items: ['one', 'two', 'three', 'four', 'five', 'six', 'seven', 'eight', 'nine', 'ten'],
        ai_prompts: ['Say the number: {word}', 'Count: {word}'],
      },
      passThreshold: 80,
      targetPhonemes: ['θ', 'v', 'f'],
      tags: ['numbers', 'beginner'],
    },
    {
      level: 1,
      levelName: 'Words',
      difficulty: DifficultyLevel.beginner,
      orderIndex: 4,
      type: 'word',
      title: 'Family',
      content: {
        items: ['mom', 'dad', 'brother', 'sister', 'baby', 'grandma', 'grandpa'],
        ai_prompts: ['Who is this? Say: {word}', 'Repeat: {word}'],
      },
      passThreshold: 80,
      targetPhonemes: ['ð', 'b', 's'],
      tags: ['family', 'beginner'],
    },
    {
      level: 1,
      levelName: 'Words',
      difficulty: DifficultyLevel.beginner,
      orderIndex: 5,
      type: 'word',
      title: 'Food',
      content: {
        items: ['apple', 'banana', 'bread', 'milk', 'egg', 'rice', 'water', 'juice'],
        ai_prompts: ['Say the food: {word}', 'What is this? {word}'],
      },
      passThreshold: 80,
      targetPhonemes: ['dʒ', 'w', 'r'],
      tags: ['food', 'beginner'],
    },
    {
      level: 1,
      levelName: 'Words',
      difficulty: DifficultyLevel.beginner,
      orderIndex: 6,
      type: 'word',
      title: 'Body Parts',
      content: {
        items: ['head', 'hand', 'foot', 'eye', 'ear', 'nose', 'mouth', 'arm', 'leg'],
        ai_prompts: ['Point and say: {word}', 'What is this? {word}'],
      },
      passThreshold: 80,
      targetPhonemes: ['h', 'f', 'aɪ'],
      tags: ['body', 'beginner'],
    },
    {
      level: 1,
      levelName: 'Words',
      difficulty: DifficultyLevel.beginner,
      orderIndex: 7,
      type: 'word',
      title: 'Clothes',
      content: {
        items: ['shirt', 'pants', 'shoes', 'hat', 'dress', 'jacket', 'socks'],
        ai_prompts: ['What are you wearing? {word}', 'Say: {word}'],
      },
      passThreshold: 80,
      targetPhonemes: ['ʃ', 'dʒ', 's'],
      tags: ['clothes', 'beginner'],
    },
    {
      level: 1,
      levelName: 'Words',
      difficulty: DifficultyLevel.beginner,
      orderIndex: 8,
      type: 'word',
      title: 'Weather',
      content: {
        items: ['sun', 'rain', 'cloud', 'snow', 'wind', 'hot', 'cold'],
        ai_prompts: ["How is the weather? It's {word}", 'Say: {word}'],
      },
      passThreshold: 80,
      targetPhonemes: ['w', 'ŋ'],
      tags: ['weather', 'beginner'],
    },
    {
      level: 1,
      levelName: 'Words',
      difficulty: DifficultyLevel.beginner,
      orderIndex: 9,
      type: 'word',
      title: 'Toys',
      content: {
        items: ['ball', 'doll', 'car', 'train', 'blocks', 'teddy', 'puzzle'],
        ai_prompts: ['What toy is this? {word}', 'Say: {word}'],
      },
      passThreshold: 80,
      targetPhonemes: ['b', 'tr', 'z'],
      tags: ['toys', 'beginner'],
    },
    {
      level: 1,
      levelName: 'Words',
      difficulty: DifficultyLevel.beginner,
      orderIndex: 10,
      type: 'word',
      title: 'Actions',
      content: {
        items: ['run', 'jump', 'walk', 'sit', 'stand', 'sleep', 'eat', 'drink'],
        ai_prompts: ['What are you doing? {word}', 'Say the action: {word}'],
      },
      passThreshold: 80,
      targetPhonemes: ['dʒ', 'w', 'sl'],
      tags: ['actions', 'verbs', 'beginner'],
    },

    // ==================== LEVEL 2: Phrases (10 lessons) ====================
    {
      level: 2,
      levelName: 'Phrases',
      difficulty: DifficultyLevel.elementary,
      orderIndex: 1,
      type: 'phrase',
      title: 'Greetings',
      content: {
        items: ['Hello', 'Good morning', 'Good night', 'How are you', 'Nice to meet you'],
        ai_prompts: ['Say: {phrase}', 'Greet me: {phrase}'],
      },
      passThreshold: 75,
      targetPhonemes: ['h', 'ŋ', 'j'],
      tags: ['greetings', 'elementary'],
    },
    {
      level: 2,
      levelName: 'Phrases',
      difficulty: DifficultyLevel.elementary,
      orderIndex: 2,
      type: 'phrase',
      title: 'Polite Words',
      content: {
        items: ['Please', 'Thank you', 'You are welcome', 'Excuse me', 'I am sorry'],
        ai_prompts: ['Be polite: {phrase}', 'Say: {phrase}'],
      },
      passThreshold: 75,
      targetPhonemes: ['θ', 'ŋ', 'z'],
      tags: ['polite', 'manners', 'elementary'],
    },
    {
      level: 2,
      levelName: 'Phrases',
      difficulty: DifficultyLevel.elementary,
      orderIndex: 3,
      type: 'phrase',
      title: 'Self Introduction',
      content: {
        items: ['My name is', 'I am eight years old', 'I live in', 'I like', 'My favorite'],
        ai_prompts: ['Tell me about yourself: {phrase}', 'Say: {phrase}'],
      },
      passThreshold: 75,
      targetPhonemes: ['aɪ', 'eɪ', 'v'],
      tags: ['introduction', 'elementary'],
    },
    {
      level: 2,
      levelName: 'Phrases',
      difficulty: DifficultyLevel.elementary,
      orderIndex: 4,
      type: 'phrase',
      title: 'At School',
      content: {
        items: ['Open your book', 'Close the door', 'Sit down please', 'Stand up', 'Raise your hand'],
        ai_prompts: ['What does teacher say? {phrase}', 'Say: {phrase}'],
      },
      passThreshold: 75,
      targetPhonemes: ['ð', 'z', 'pl'],
      tags: ['school', 'classroom', 'elementary'],
    },
    {
      level: 2,
      levelName: 'Phrases',
      difficulty: DifficultyLevel.elementary,
      orderIndex: 5,
      type: 'phrase',
      title: 'Asking Questions',
      content: {
        items: ['What is this', 'Where is it', 'How much', 'Can I have', 'May I go'],
        ai_prompts: ['Ask a question: {phrase}', 'Say: {phrase}'],
      },
      passThreshold: 75,
      targetPhonemes: ['w', 'h', 'ð'],
      tags: ['questions', 'elementary'],
    },
    {
      level: 2,
      levelName: 'Phrases',
      difficulty: DifficultyLevel.elementary,
      orderIndex: 6,
      type: 'phrase',
      title: 'Daily Activities',
      content: {
        items: ['I wake up', 'I brush my teeth', 'I eat breakfast', 'I go to school', 'I do homework'],
        ai_prompts: ['What do you do? {phrase}', 'Say: {phrase}'],
      },
      passThreshold: 75,
      targetPhonemes: ['br', 'sk', 'θ'],
      tags: ['daily', 'routine', 'elementary'],
    },
    {
      level: 2,
      levelName: 'Phrases',
      difficulty: DifficultyLevel.elementary,
      orderIndex: 7,
      type: 'phrase',
      title: 'At Home',
      content: {
        items: ['In the kitchen', 'On the table', 'Under the bed', 'Next to the door', 'Behind the chair'],
        ai_prompts: ['Where is it? {phrase}', 'Say: {phrase}'],
      },
      passThreshold: 75,
      targetPhonemes: ['ð', 'tʃ', 'n'],
      tags: ['home', 'prepositions', 'elementary'],
    },
    {
      level: 2,
      levelName: 'Phrases',
      difficulty: DifficultyLevel.elementary,
      orderIndex: 8,
      type: 'phrase',
      title: 'Feelings',
      content: {
        items: ['I am happy', 'I am sad', 'I am tired', 'I am hungry', 'I am thirsty'],
        ai_prompts: ['How do you feel? {phrase}', 'Say: {phrase}'],
      },
      passThreshold: 75,
      targetPhonemes: ['θ', 'ŋ', 'aɪ'],
      tags: ['feelings', 'emotions', 'elementary'],
    },
    {
      level: 2,
      levelName: 'Phrases',
      difficulty: DifficultyLevel.elementary,
      orderIndex: 9,
      type: 'phrase',
      title: 'Shopping',
      content: {
        items: ['How much is it', 'I want to buy', 'Do you have', 'Too expensive', 'I will take it'],
        ai_prompts: ['At the store: {phrase}', 'Say: {phrase}'],
      },
      passThreshold: 75,
      targetPhonemes: ['tʃ', 'w', 'ks'],
      tags: ['shopping', 'money', 'elementary'],
    },
    {
      level: 2,
      levelName: 'Phrases',
      difficulty: DifficultyLevel.elementary,
      orderIndex: 10,
      type: 'phrase',
      title: 'Playing',
      content: {
        items: ["Let's play", 'Your turn', 'My turn', 'I win', 'Good game'],
        ai_prompts: ['Playing with friends: {phrase}', 'Say: {phrase}'],
      },
      passThreshold: 75,
      targetPhonemes: ['l', 'w', 'ŋ'],
      tags: ['play', 'games', 'elementary'],
    },

    // ==================== LEVEL 3: Sentences (10 lessons) ====================
    {
      level: 3,
      levelName: 'Sentences',
      difficulty: DifficultyLevel.intermediate,
      orderIndex: 1,
      type: 'sentence',
      title: 'About Me',
      content: {
        items: [
          'My name is Anna and I am nine years old.',
          'I have a brother and a sister.',
          'My favorite color is blue.',
          'I like to play soccer.',
          'I go to school every day.',
        ],
        ai_prompts: ['Tell me about yourself. Say: {sentence}'],
      },
      passThreshold: 70,
      targetPhonemes: ['θ', 'v', 'ð'],
      tags: ['introduction', 'intermediate'],
    },
    {
      level: 3,
      levelName: 'Sentences',
      difficulty: DifficultyLevel.intermediate,
      orderIndex: 2,
      type: 'sentence',
      title: 'My Family',
      content: {
        items: [
          'My mother works at a hospital.',
          'My father is a teacher.',
          'My grandparents live in the countryside.',
          'I love my family very much.',
          'We eat dinner together every night.',
        ],
        ai_prompts: ['Tell me about your family. Say: {sentence}'],
      },
      passThreshold: 70,
      targetPhonemes: ['ð', 'v', 'ŋ'],
      tags: ['family', 'intermediate'],
    },
    {
      level: 3,
      levelName: 'Sentences',
      difficulty: DifficultyLevel.intermediate,
      orderIndex: 3,
      type: 'sentence',
      title: 'At School',
      content: {
        items: [
          'I study English and Math at school.',
          'My favorite subject is Science.',
          'The teacher explains the lesson clearly.',
          'I do my homework after school.',
          'We have a test tomorrow.',
        ],
        ai_prompts: ['Tell me about school. Say: {sentence}'],
      },
      passThreshold: 70,
      targetPhonemes: ['ʃ', 'tʃ', 'sk'],
      tags: ['school', 'intermediate'],
    },
    {
      level: 3,
      levelName: 'Sentences',
      difficulty: DifficultyLevel.intermediate,
      orderIndex: 4,
      type: 'sentence',
      title: 'My Hobbies',
      content: {
        items: [
          'I like reading books in my free time.',
          'Playing video games is fun.',
          'I enjoy drawing pictures.',
          'Swimming is my favorite sport.',
          'I practice piano every day.',
        ],
        ai_prompts: ['What do you like to do? Say: {sentence}'],
      },
      passThreshold: 70,
      targetPhonemes: ['dʒ', 'ŋ', 'aɪ'],
      tags: ['hobbies', 'intermediate'],
    },
    {
      level: 3,
      levelName: 'Sentences',
      difficulty: DifficultyLevel.intermediate,
      orderIndex: 5,
      type: 'sentence',
      title: 'Weather Talk',
      content: {
        items: [
          'It is sunny today.',
          'I think it will rain tomorrow.',
          'The weather is very hot in summer.',
          'I like winter because I can play in the snow.',
          'We need an umbrella when it rains.',
        ],
        ai_prompts: ['Talk about the weather. Say: {sentence}'],
      },
      passThreshold: 70,
      targetPhonemes: ['ð', 'w', 'z'],
      tags: ['weather', 'intermediate'],
    },
    {
      level: 3,
      levelName: 'Sentences',
      difficulty: DifficultyLevel.intermediate,
      orderIndex: 6,
      type: 'sentence',
      title: 'Food and Eating',
      content: {
        items: [
          'I had rice and chicken for lunch.',
          'My mother cooks delicious food.',
          'I drink milk every morning.',
          'Vegetables are good for your health.',
          'Can I have some water please?',
        ],
        ai_prompts: ['Talk about food. Say: {sentence}'],
      },
      passThreshold: 70,
      targetPhonemes: ['tʃ', 'v', 'ð'],
      tags: ['food', 'intermediate'],
    },
    {
      level: 3,
      levelName: 'Sentences',
      difficulty: DifficultyLevel.intermediate,
      orderIndex: 7,
      type: 'sentence',
      title: 'Asking for Help',
      content: {
        items: [
          'Could you help me with this problem?',
          'I do not understand this question.',
          'Can you explain it again please?',
          'Where is the bathroom?',
          'How do I get to the library?',
        ],
        ai_prompts: ['Ask for help. Say: {sentence}'],
      },
      passThreshold: 70,
      targetPhonemes: ['θ', 'ð', 'h'],
      tags: ['help', 'questions', 'intermediate'],
    },
    {
      level: 3,
      levelName: 'Sentences',
      difficulty: DifficultyLevel.intermediate,
      orderIndex: 8,
      type: 'sentence',
      title: 'Making Plans',
      content: {
        items: [
          'What are you doing this weekend?',
          'I am going to visit my grandparents.',
          'Let us go to the park together.',
          'We should watch a movie tonight.',
          'I will call you tomorrow.',
        ],
        ai_prompts: ['Make a plan. Say: {sentence}'],
      },
      passThreshold: 70,
      targetPhonemes: ['ð', 'ŋ', 'ʃ'],
      tags: ['plans', 'future', 'intermediate'],
    },
    {
      level: 3,
      levelName: 'Sentences',
      difficulty: DifficultyLevel.intermediate,
      orderIndex: 9,
      type: 'sentence',
      title: 'Describing Things',
      content: {
        items: [
          'The cat is sleeping on the sofa.',
          'This book is very interesting.',
          'My room is small but comfortable.',
          'The flower smells beautiful.',
          'That building is really tall.',
        ],
        ai_prompts: ['Describe something. Say: {sentence}'],
      },
      passThreshold: 70,
      targetPhonemes: ['ð', 'θ', 'fl'],
      tags: ['description', 'adjectives', 'intermediate'],
    },
    {
      level: 3,
      levelName: 'Sentences',
      difficulty: DifficultyLevel.intermediate,
      orderIndex: 10,
      type: 'sentence',
      title: 'Past Events',
      content: {
        items: [
          'Yesterday I went to the zoo.',
          'Last week we had a birthday party.',
          'I watched a movie last night.',
          'My friend gave me a present.',
          'We played soccer in the park.',
        ],
        ai_prompts: ['Tell me what happened. Say: {sentence}'],
      },
      passThreshold: 70,
      targetPhonemes: ['d', 't', 'ŋ'],
      tags: ['past', 'events', 'intermediate'],
    },

    // ==================== LEVEL 4: Dialogues (10 lessons) ====================
    {
      level: 4,
      levelName: 'Dialogues',
      difficulty: DifficultyLevel.upper_intermediate,
      orderIndex: 1,
      type: 'dialogue',
      title: 'Meeting New Friends',
      content: {
        exchanges: [
          { ai: 'Hi! What is your name?', expected_user: ['My name is...', 'I am...'] },
          { ai: 'Nice to meet you! How old are you?', expected_user: ['I am ... years old', 'I am ...'] },
          { ai: 'What school do you go to?', expected_user: ['I go to...', 'I study at...'] },
        ],
        ai_prompts: ['Let us have a conversation. Answer my question.'],
      },
      passThreshold: 65,
      targetPhonemes: ['w', 'j', 'ð'],
      tags: ['meeting', 'conversation', 'upper_intermediate'],
    },
    {
      level: 4,
      levelName: 'Dialogues',
      difficulty: DifficultyLevel.upper_intermediate,
      orderIndex: 2,
      type: 'dialogue',
      title: 'At the Restaurant',
      content: {
        exchanges: [
          { ai: 'Welcome! How many people?', expected_user: ['Two people please', 'Just me', 'Three'] },
          { ai: 'What would you like to order?', expected_user: ['I would like...', 'Can I have...'] },
          { ai: 'Anything to drink?', expected_user: ['Water please', 'Orange juice', 'No thank you'] },
        ],
        ai_prompts: ['You are at a restaurant. Answer the waiter.'],
      },
      passThreshold: 65,
      targetPhonemes: ['w', 'dʒ', 'θ'],
      tags: ['restaurant', 'ordering', 'upper_intermediate'],
    },
    {
      level: 4,
      levelName: 'Dialogues',
      difficulty: DifficultyLevel.upper_intermediate,
      orderIndex: 3,
      type: 'dialogue',
      title: 'Shopping for Clothes',
      content: {
        exchanges: [
          { ai: 'Can I help you?', expected_user: ['I am looking for...', 'Do you have...'] },
          { ai: 'What size do you need?', expected_user: ['Small please', 'Medium', 'Large'] },
          { ai: 'How about this one?', expected_user: ['I like it', 'Do you have another color', 'Too expensive'] },
        ],
        ai_prompts: ['You are shopping. Talk to the salesperson.'],
      },
      passThreshold: 65,
      targetPhonemes: ['ʃ', 'z', 'ð'],
      tags: ['shopping', 'clothes', 'upper_intermediate'],
    },
    {
      level: 4,
      levelName: 'Dialogues',
      difficulty: DifficultyLevel.upper_intermediate,
      orderIndex: 4,
      type: 'dialogue',
      title: 'Asking for Directions',
      content: {
        exchanges: [
          { ai: 'Excuse me, can I help you?', expected_user: ['Where is the...', 'How do I get to...'] },
          { ai: 'Go straight and turn left at the corner.', expected_user: ['Thank you', 'Is it far', 'How long does it take'] },
          { ai: 'You are welcome! Have a nice day!', expected_user: ['You too', 'Thank you', 'Goodbye'] },
        ],
        ai_prompts: ['You are lost. Ask for directions.'],
      },
      passThreshold: 65,
      targetPhonemes: ['ð', 'str', 'l'],
      tags: ['directions', 'travel', 'upper_intermediate'],
    },
    {
      level: 4,
      levelName: 'Dialogues',
      difficulty: DifficultyLevel.upper_intermediate,
      orderIndex: 5,
      type: 'dialogue',
      title: 'At the Doctor',
      content: {
        exchanges: [
          { ai: 'What seems to be the problem?', expected_user: ['I have a headache', 'My stomach hurts', 'I feel sick'] },
          { ai: 'How long have you felt this way?', expected_user: ['Since yesterday', 'For two days', 'This morning'] },
          { ai: 'Take this medicine twice a day.', expected_user: ['Thank you doctor', 'Okay', 'How many times'] },
        ],
        ai_prompts: ['You are at the doctor. Describe how you feel.'],
      },
      passThreshold: 65,
      targetPhonemes: ['θ', 'tʃ', 'h'],
      tags: ['health', 'doctor', 'upper_intermediate'],
    },
    {
      level: 4,
      levelName: 'Dialogues',
      difficulty: DifficultyLevel.upper_intermediate,
      orderIndex: 6,
      type: 'dialogue',
      title: 'Making a Phone Call',
      content: {
        exchanges: [
          { ai: 'Hello?', expected_user: ['Hi, this is...', 'Hello, may I speak to...'] },
          { ai: 'How can I help you?', expected_user: ['I am calling about...', 'I wanted to ask...'] },
          { ai: 'Sure, I can help with that.', expected_user: ['Thank you', 'That would be great'] },
        ],
        ai_prompts: ['You are making a phone call.'],
      },
      passThreshold: 65,
      targetPhonemes: ['ð', 'θ', 'h'],
      tags: ['phone', 'communication', 'upper_intermediate'],
    },
    {
      level: 4,
      levelName: 'Dialogues',
      difficulty: DifficultyLevel.upper_intermediate,
      orderIndex: 7,
      type: 'dialogue',
      title: 'Planning a Trip',
      content: {
        exchanges: [
          { ai: 'Where do you want to go?', expected_user: ['I want to go to...', 'How about...', 'Let us go to...'] },
          { ai: 'When should we go?', expected_user: ['This weekend', 'Next month', 'In summer'] },
          { ai: 'How will we get there?', expected_user: ['By car', 'By plane', 'By train'] },
        ],
        ai_prompts: ['Plan a trip with your friend.'],
      },
      passThreshold: 65,
      targetPhonemes: ['w', 'ð', 'tr'],
      tags: ['travel', 'planning', 'upper_intermediate'],
    },
    {
      level: 4,
      levelName: 'Dialogues',
      difficulty: DifficultyLevel.upper_intermediate,
      orderIndex: 8,
      type: 'dialogue',
      title: 'Birthday Party',
      content: {
        exchanges: [
          { ai: 'Happy birthday! How old are you now?', expected_user: ['Thank you', 'I am ... years old'] },
          { ai: 'What present did you get?', expected_user: ['I got a...', 'My parents gave me...'] },
          { ai: 'Let us cut the cake!', expected_user: ['Yes', 'I love cake', 'Make a wish'] },
        ],
        ai_prompts: ['It is your birthday party.'],
      },
      passThreshold: 65,
      targetPhonemes: ['θ', 'ð', 'dʒ'],
      tags: ['birthday', 'celebration', 'upper_intermediate'],
    },
    {
      level: 4,
      levelName: 'Dialogues',
      difficulty: DifficultyLevel.upper_intermediate,
      orderIndex: 9,
      type: 'dialogue',
      title: 'At the Library',
      content: {
        exchanges: [
          { ai: 'Can I help you find something?', expected_user: ['I am looking for...', 'Where are the...'] },
          { ai: 'You can find it in section B.', expected_user: ['Thank you', 'Where is section B'] },
          { ai: 'Would you like to borrow this book?', expected_user: ['Yes please', 'How long can I keep it'] },
        ],
        ai_prompts: ['You are at the library.'],
      },
      passThreshold: 65,
      targetPhonemes: ['θ', 'ð', 'br'],
      tags: ['library', 'books', 'upper_intermediate'],
    },
    {
      level: 4,
      levelName: 'Dialogues',
      difficulty: DifficultyLevel.upper_intermediate,
      orderIndex: 10,
      type: 'dialogue',
      title: 'Job Interview (Simple)',
      content: {
        exchanges: [
          { ai: 'Tell me about yourself.', expected_user: ['My name is...', 'I am a student...'] },
          { ai: 'Why do you want this job?', expected_user: ['I like...', 'I want to learn...', 'Because...'] },
          { ai: 'When can you start?', expected_user: ['Right away', 'Next week', 'Anytime'] },
        ],
        ai_prompts: ['Practice a simple job interview.'],
      },
      passThreshold: 65,
      targetPhonemes: ['dʒ', 'w', 'ð'],
      tags: ['interview', 'job', 'upper_intermediate'],
    },

    // ==================== LEVEL 5: Free Talk (10 lessons) ====================
    {
      level: 5,
      levelName: 'Free Talk',
      difficulty: DifficultyLevel.advanced,
      orderIndex: 1,
      type: 'free',
      title: 'My Dream',
      content: {
        topics: ['my dream', 'what I want to be', 'future plans'],
        ai_prompts: ['Tell me about {topic}. Speak freely for 30 seconds.'],
        min_duration: 20,
      },
      passThreshold: 60,
      targetPhonemes: ['dr', 'w', 'θ'],
      tags: ['dreams', 'future', 'advanced'],
    },
    {
      level: 5,
      levelName: 'Free Talk',
      difficulty: DifficultyLevel.advanced,
      orderIndex: 2,
      type: 'free',
      title: 'My Best Friend',
      content: {
        topics: ['my best friend', 'friendship', 'what we do together'],
        ai_prompts: ['Tell me about {topic}. Describe your friend.'],
        min_duration: 20,
      },
      passThreshold: 60,
      targetPhonemes: ['fr', 'ð', 'ŋ'],
      tags: ['friends', 'relationships', 'advanced'],
    },
    {
      level: 5,
      levelName: 'Free Talk',
      difficulty: DifficultyLevel.advanced,
      orderIndex: 3,
      type: 'free',
      title: 'Favorite Movie',
      content: {
        topics: ['my favorite movie', 'the story', 'why I like it'],
        ai_prompts: ['Tell me about {topic}. What happens in the movie?'],
        min_duration: 20,
      },
      passThreshold: 60,
      targetPhonemes: ['v', 'st', 'aɪ'],
      tags: ['movies', 'entertainment', 'advanced'],
    },
    {
      level: 5,
      levelName: 'Free Talk',
      difficulty: DifficultyLevel.advanced,
      orderIndex: 4,
      type: 'free',
      title: 'Weekend Activities',
      content: {
        topics: ['what I did last weekend', 'my weekend plans', 'favorite weekend activity'],
        ai_prompts: ['Tell me about {topic}. What do you usually do?'],
        min_duration: 20,
      },
      passThreshold: 60,
      targetPhonemes: ['w', 'dʒ', 'ð'],
      tags: ['weekend', 'activities', 'advanced'],
    },
    {
      level: 5,
      levelName: 'Free Talk',
      difficulty: DifficultyLevel.advanced,
      orderIndex: 5,
      type: 'free',
      title: 'My Pet',
      content: {
        topics: ['my pet', 'animals I like', 'taking care of pets'],
        ai_prompts: ['Tell me about {topic}. Do you have a pet?'],
        min_duration: 20,
      },
      passThreshold: 60,
      targetPhonemes: ['p', 'k', 'ð'],
      tags: ['pets', 'animals', 'advanced'],
    },
    {
      level: 5,
      levelName: 'Free Talk',
      difficulty: DifficultyLevel.advanced,
      orderIndex: 6,
      type: 'free',
      title: 'Favorite Food',
      content: {
        topics: ['my favorite food', 'cooking', 'healthy eating'],
        ai_prompts: ['Tell me about {topic}. What do you like to eat?'],
        min_duration: 20,
      },
      passThreshold: 60,
      targetPhonemes: ['f', 'v', 'ð'],
      tags: ['food', 'cooking', 'advanced'],
    },
    {
      level: 5,
      levelName: 'Free Talk',
      difficulty: DifficultyLevel.advanced,
      orderIndex: 7,
      type: 'free',
      title: 'Special Holiday',
      content: {
        topics: ['my favorite holiday', 'how we celebrate', 'holiday memories'],
        ai_prompts: ['Tell me about {topic}. How do you celebrate?'],
        min_duration: 20,
      },
      passThreshold: 60,
      targetPhonemes: ['h', 'θ', 'ð'],
      tags: ['holidays', 'celebration', 'advanced'],
    },
    {
      level: 5,
      levelName: 'Free Talk',
      difficulty: DifficultyLevel.advanced,
      orderIndex: 8,
      type: 'free',
      title: 'Sports I Play',
      content: {
        topics: ['sports I play', 'my favorite team', 'being healthy'],
        ai_prompts: ['Tell me about {topic}. Do you play any sports?'],
        min_duration: 20,
      },
      passThreshold: 60,
      targetPhonemes: ['sp', 'pl', 'θ'],
      tags: ['sports', 'health', 'advanced'],
    },
    {
      level: 5,
      levelName: 'Free Talk',
      difficulty: DifficultyLevel.advanced,
      orderIndex: 9,
      type: 'free',
      title: 'My Room',
      content: {
        topics: ['my room', 'my favorite things', 'where I study'],
        ai_prompts: ['Tell me about {topic}. Describe your room.'],
        min_duration: 20,
      },
      passThreshold: 60,
      targetPhonemes: ['r', 'θ', 'ŋ'],
      tags: ['home', 'personal', 'advanced'],
    },
    {
      level: 5,
      levelName: 'Free Talk',
      difficulty: DifficultyLevel.advanced,
      orderIndex: 10,
      type: 'free',
      title: 'My Neighborhood',
      content: {
        topics: ['my neighborhood', 'places near my home', 'my neighbors'],
        ai_prompts: ['Tell me about {topic}. What is it like where you live?'],
        min_duration: 20,
      },
      passThreshold: 60,
      targetPhonemes: ['n', 'ð', 'h'],
      tags: ['neighborhood', 'community', 'advanced'],
    },
  ];

  // Upsert all lessons
  for (const lesson of lessons) {
    const lessonId = `sp-lesson-L${lesson.level}-${lesson.orderIndex}`;
    const mapping = lessonCategoryMap[lessonId];

    await prisma.speakingPracticeLesson.upsert({
      where: {
        id: lessonId,
      },
      update: {
        ...lesson,
        category: mapping?.category,
        difficultyTier: mapping?.tier,
        isTemplate: true,
        isActive: true,
      },
      create: {
        id: lessonId,
        ...lesson,
        category: mapping?.category,
        difficultyTier: mapping?.tier,
        isTemplate: true,
        isActive: true,
      },
    });
  }

  console.log(`✅ Seeded ${lessons.length} Speaking Practice Lessons`);
  return lessons.length;
}

// Run if called directly
if (require.main === module) {
  seedSpeakingPracticeLessons()
    .then((count) => {
      console.log(`Done! Created ${count} lessons.`);
      process.exit(0);
    })
    .catch((e) => {
      console.error(e);
      process.exit(1);
    });
}
