import { PayloadToken } from '@app/shared';
import {
  Body,
  Controller,
  FileTypeValidator,
  Get,
  MaxFileSizeValidator,
  Param,
  ParseFilePipe,
  Post,
  Query,
  UploadedFile,
  UseInterceptors,
} from '@nestjs/common';
import { FileInterceptor } from '@nestjs/platform-express';
import {
  GetDrillsDto,
  GetNextItemDto,
  NextPracticeItemDto,
  PersonalizedDrillDto,
  SpeakingPracticeProgressDto,
  SubmitAttemptDto,
  SubmitResultDto,
} from './dto/speaking-practice-api.dto';
import {
  TopicListResponseDto,
  LessonsByCategoryResponseDto,
  LessonRecommendation,
} from './dto/topic-based.dto';
import {
  PlacementTestStatusDto,
  StartPlacementTestResponseDto,
  SubmitTestResponseDto,
  PlacementTestResultDto,
  ItemsRemainingDto,
} from './dto/placement-test.dto';
import { SpeakingPracticeService } from './service/speaking-practice.service';
import { PlacementTestService } from './services/placement-test/placement-test.service';

/**
 * Speaking Practice Controller
 * REST API for Progress-Based AI Speaking Practice
 *
 * Endpoints:
 * - GET  /speaking-practice/current    → Get user's progress
 * - GET  /speaking-practice/next-item  → Get next practice item
 * - POST /speaking-practice/submit     → Submit practice attempt
 * - GET  /speaking-practice/drills     → Get personalized drills
 */
@Controller('/private/v1/speaking-practice')
export class SpeakingPracticeController {
  constructor(
    private readonly service: SpeakingPracticeService,
    private readonly placementTestService: PlacementTestService,
  ) {}

  /**
   * GET /speaking-practice/current
   * Get user's current speaking practice progress
   *
   * @returns User's progress including level, completed lessons, weak phonemes
   */
  @Get('current')
  async getCurrentProgress(
    @PayloadToken('sub') userId: string,
  ): Promise<SpeakingPracticeProgressDto> {
    return this.service.getCurrentProgress(userId);
  }

  /**
   * GET /speaking-practice/next-item
   * Get next practice item for user to speak
   *
   * @param query Optional: level override, specific lessonId, include remedial
   * @returns Next practice item with content, prompt, reference text
   */
  @Get('next-item')
  async getNextItem(
        @PayloadToken('sub') userId: string,

    @Query() query: GetNextItemDto,
  ): Promise<NextPracticeItemDto> {
    return this.service.getNextItem(userId, {
      level: query.level,
      lessonId: query.lessonId,
      includeRemedial: query.includeRemedial,
    });
  }

  /**
   * POST /speaking-practice/submit
   * Submit practice attempt with audio recording
   *
   * @param dto Submission details (lessonId, itemIndex, referenceText)
   * @param file Audio file (WEBM, WAV, MP3)
   * @returns Scoring result with feedback and next action
   */
  @Post('submit')
  @UseInterceptors(FileInterceptor('audio'))
  async submitAttempt(
       @PayloadToken('sub') userId: string,

    @Body() dto: SubmitAttemptDto,
    @UploadedFile(
      new ParseFilePipe({
        validators: [
          new MaxFileSizeValidator({ maxSize: 10 * 1024 * 1024 }), // 10MB max
          new FileTypeValidator({
            fileType: /(audio\/(webm|wav|mp3|ogg|mpeg)|application\/octet-stream)/,
          }),
        ],
        fileIsRequired: false, // Allow base64 alternative
      }),
    )
    file?: Express.Multer.File,
  ): Promise<SubmitResultDto> {
    // Get audio buffer from file or base64
    let audioBuffer: Buffer;
    if (file) {
      audioBuffer = file.buffer;
    } else if (dto.audioBase64) {
      audioBuffer = Buffer.from(dto.audioBase64, 'base64');
    } else {
      throw new Error('Audio file or audioBase64 is required');
    }

    return this.service.submitAttempt(userId, dto, audioBuffer);
  }

  /**
   * GET /speaking-practice/drills
   * Get personalized drills generated by LLM
   *
   * @param query Optional: status filter, limit
   * @returns List of personalized drills with target words and sentences
   */
  @Get('drills')
  async getPersonalizedDrills(
    @PayloadToken('sub') userId: string,

    @Query() query: GetDrillsDto,
  ): Promise<PersonalizedDrillDto[]> {
    return this.service.getPersonalizedDrills(userId, {
      status: query.status,
      limit: query.limit,
    });
  }

  /**
   * GET /speaking-practice/due-words
   * Get words due for SM-2 spaced repetition review
   *
   * @param query Optional: limit, offset for pagination
   * @returns List of words due for review with SRS stats
   */
  @Get('due-words')
  async getDueWordsForReview(
    @PayloadToken('sub') userId: string,

    @Query('limit') limit?: number,
    @Query('offset') offset?: number,
  ) {
    return this.service.getDueWordsForReview(userId, {
      limit: limit ? Number(limit) : 20,
      offset: offset ? Number(offset) : 0,
    });
  }

  /**
   * GET /speaking-practice/topics
   * Get all topic categories with progress summary
   *
   * @returns List of topics with completion status, scores, tier progress
   */
  @Get('topics')
  async getTopics(@PayloadToken('sub') userId: string): Promise<TopicListResponseDto> {
    return this.service.getTopicList(userId);
  }

  /**
   * GET /speaking-practice/topics/:category/lessons
   * Get lessons in a specific category with progress
   *
   * @param category Topic category name
   * @returns Lessons in category ordered by tier
   */
  @Get('topics/:category/lessons')
  async getLessonsByCategory(
    @Param('category') category: string,
    @PayloadToken('sub') userId: string,
  ): Promise<LessonsByCategoryResponseDto> {
    return this.service.getLessonsByCategory(userId, category);
  }

  /**
   * GET /speaking-practice/recommendations
   * Get personalized lesson recommendations based on performance
   *
   * @param query Optional: limit for number of recommendations
   * @returns Recommended lessons with priority and reason
   */
  @Get('recommendations')
  async getRecommendations(
    @PayloadToken('sub') userId: string,
    @Query('limit') limit?: number,
  ): Promise<LessonRecommendation[]> {
    return this.service.getRecommendations(userId, limit ? Number(limit) : 5);
  }

  /**
   * GET /speaking-practice/placement-test
   * Get placement test status for current user
   *
   * @returns Placement test status including completion status and results
   */
  @Get('placement-test')
  async getPlacementTest(
    @PayloadToken('sub') userId: string,
  ): Promise<PlacementTestStatusDto> {
    return await this.placementTestService.getPlacementTest(userId);
  }

  /**
   * POST /speaking-practice/placement-test/start
   * Start a new placement test
   *
   * @returns Test items for pronunciation assessment
   */
  @Post('placement-test/start')
  async startPlacementTest(
    @PayloadToken('sub') userId: string,
  ): Promise<StartPlacementTestResponseDto> {
    return await this.placementTestService.startPlacementTest(userId);
  }

  /**
   * POST /speaking-practice/placement-test/submit
   * Submit a single test item response
   *
   * @param dto Test response with itemId, score, transcript
   * @returns Number of items remaining in test
   */
  @Post('placement-test/submit')
  async submitTestResponse(
    @PayloadToken('sub') userId: string,
    @Body() dto: SubmitTestResponseDto,
  ): Promise<ItemsRemainingDto> {
    return await this.placementTestService.submitTestResponse(
      userId,
      dto.itemId,
      dto.score,
      dto.transcript,
    );
  }

  /**
   * POST /speaking-practice/placement-test/complete
   * Complete the placement test and get results
   *
   * @returns Test results with overall level, phoneme scores, topic recommendations
   */
  @Post('placement-test/complete')
  async completePlacementTest(
    @PayloadToken('sub') userId: string,
  ): Promise<PlacementTestResultDto> {
    return await this.placementTestService.completePlacementTest(userId);
  }
}
